### ISSUE TITLE
Missing LICENSE.md

### ISSUE THREAD

**Issue by enzanki-ars** [diogotr7/AuroraGSI-RocketLeague#1]
I have been working on repurposing this for one of [my own projects ](https://github.com/enzanki-ars/StreamGraphicsGSI-RL), and just noticed that this repository does not have a LICENSE.  Could you please set a license so that I can ensure that I am abiding by the principles you have in mind for the reuse of your code?

**Comment by diogotr7** [comment]
Sorry about that! Just added a license :)
